job1:
  image: docker:19.03.12

  before_script:
    - docker info

  build:
    stage: build
    script:
      - docker build -t qnap:forum-crawler .
  tags:
    - x86

job2:
  image: docker:19.03.12

  before_script:
    - docker info

  build:
    stage: build
    script:
      - docker build -t qnap:forum-crawler .
  tags:
    - arm64