image: docker:19.03.12

before_script:
  - docker info

x86-build:
  stage: build
  script:
    - docker build -t qnap:forum-crawler .
  tags:
    - x86

arm64-build:
  stage: build
  script:
    - docker build -t qnap:forum-crawler .
  tags:
    - arm64