{
 "title": "Surveillance Solution",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "新文章",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT metadata.*\r\nFROM (\r\nSELECT id FROM (SELECT * FROM date_rank WHERE _date=FROM_UNIXTIME($__unixEpochTo(),'%Y-%m-%d')) AS T1\r\nWHERE id NOT IN (SELECT id FROM date_rank WHERE _date=FROM_UNIXTIME($__unixEpochFrom(),'%Y-%m-%d'))\r\n) AS T2\r\nJOIN metadata\r\nON T2.id=metadata.id"
    }
   ]
  },
  {
   "title": "每日總文章數",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  a._date AS time,\n  COUNT(a._date) AS \"Topic Count\"\nFROM date_rank as a\nWHERE _date>=$__timeFrom() AND _date<=$__timeTo()\nGROUP BY a._date\nORDER BY time\nASC\n"
    }
   ]
  },
  {
   "title": "前20名次數",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  date_rank.id AS ID,\r\n  metadata.topic AS Topic,\r\n  COUNT(date_rank.rank) AS \"Top20 Count\",\r\n  metadata.link AS Link\r\nFROM date_rank\r\nJOIN metadata\r\nON date_rank.id=metadata.id\r\nWHERE _date>=$__timeFrom() AND _date<=$__timeTo() AND date_rank.rank<20\r\nGROUP BY id\r\nORDER BY \"Top20 Count\"\r\nDESC\r\n"
    }
   ]
  },
  {
   "title": "日新增數",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select a._date AS time,  (a.topic_count-b.topic_count) AS \"Count\" from (\n\t(SELECT (@an := @an + 1) as id, ta._date, COUNT(ta._date) AS \"topic_count\" FROM date_rank as ta, (SELECT @an := -1) AS ita GROUP BY ta._date ORDER BY ta._date DESC \n\t) AS a, \n\t(SELECT (@bn := @bn + 1) AS id, tb._date, COUNT(tb._date) AS \"topic_count\" FROM date_rank AS tb, (SELECT @bn := -1) AS itb GROUP BY tb._date ORDER BY tb._date DESC \n\t) AS b\n\t)\nWHERE a.id=b.id-1 AND a._date>=$__timeFrom() AND a._date<=$__timeTo();\n"
    }
   ]
  }
 ]
}